---
output: html_document
---


<link rel=stylesheet href=style.css>
<script src=https://kit.fontawesome.com/6e8b08f469.js crossorigin=anonymous></script>

<h2><b>Publications</b></h2>

<table>
<col width=20%>
<col width=30%>
<col width=50%>

## 2024

<b>Shang Y</b>, Chiu Y, Kong L. Robust Propensity Score Estimation via Loss Function Calibration. {Statistical Methods in Medical Research}, in press. 2024

<b>Shang Y</b>, Ning J, Minagawa K, Zhou S. Non-Parametric Analysis of Transient Data: a Pseudo-Competing Event Approach''. {Statistics in Medicine} (Under Review). 2024


<b>Shang Y</b>, Chiu Y, Kong L. 2024. A Latent Variable Approach for Causal Effect Estimation under Misclassified Treatment Assignment. (Ready to submit).

<b>Shang Y</b>, Kim Y, Mt-Isa S, Li J. 2024. Assessing the performance of indirect treatment comparison methods for longitudinal outcomes. (In preparation).

Zhang R, <b>Shang Y</b>, Cioccio J... Sensitivity and specificity of chimerism tests in predicting leukemia relapse using increasing mixed chimerism''. {The Journal of Molecular Diagnostics}, Volume 26, Issue 12, 1159 - 1170

Slobodanka P, <b>Shang Y</b>, Alexandors V ... C-reactive protein improves the ability to detect hypertension and insulin resistance in mild-to-moderate obstructive sleep apnea: age effect''. {Journal of Sleep Research}, 2024; e14386

Vgontzas A, <b>Shang Y</b>, He F... 0392 Insomnia with Short Sleep Duration Is Associated with Heart Disease and Stroke: Evidence from the UK Biobank Cohort''. {Sleep}. 2024 May 1;47(Supplement\_1):A168-9.


## 2023

Che, X., Roy, A., Bresnahan, M., Mjaaland, S., Reichborn-Kjennerud, T., Magnus, P., Stoltenberg, C., <b>Shang Y</b>, Zhang, K., Susser, E., Fiehn, O., \& Lipkin, W. I. Metabolomic analysis of maternal mid-gestation plasma and cord blood in autism spectrum disorders. Molecular psychiatry, 2023; 28(6):2355–2369. doi:10.1038/s41380-023-02051-w

## 2022

Endres KM, Kierys K, <b>Shang Y</b>, et al. A Multicenter Retrospective Evaluation of Specialized Laboratory Investigations in the Workup of Pediatric Patients With New-Onset Supraventricular Tachycardia. J Emerg Nurs. 2022;48(6):678-687. doi:10.1016/j.jen.2022.07.002

## 2021

Shechter A, Chiuzan C, <b>Shang Y</b>, et al. Prevalence, Incidence, and Factors Associated with Posttraumatic Stress at Three-Month Follow-Up among New York City Healthcare Workers after the First Wave of the COVID-19 Pandemic. Int J Environ Res Public Health. 2021;19(1):262. doi:10.3390/ijerph19010262

Abdalla M, Chiuzan C, <b>Shang Y</b>, et al. Factors Associated with Insomnia Symptoms in a Longitudinal Study among New York City Healthcare Workers during the COVID-19 Pandemic. Int J Environ Res Public Health. 2021;18(17):8970. doi:10.3390/ijerph18178970