---
title: "plot"
author: "Yimeng SHANG"
date: "10/25/2019"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(p8105.datasets)

library(plotly)

data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)
```
```{r}
instacart %>%
  group_by(aisle) %>%
  summarise(number = n()) %>%
  filter(number > 10000) %>% 
  plot_ly(x =~reorder(aisle,number), y = ~number, color = ~aisle, type = "bar") %>%
  layout(title = "Total number in different aisles")
```

```{r}

box_ggplot = 
  instacart %>%
  select(product_name, order_hour_of_day) %>%
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream"|product_name == "Organic Celery Hearts"|product_name == "Spring Water"|product_name == "Bag of Organic Bananas") %>%

  ggplot(aes(x = product_name, y = order_hour_of_day, fill = product_name)) +
  labs(title = "Order time distribution") +
  geom_boxplot() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot) 
```

```{r}

  instacart %>%
  select(order_dow, order_hour_of_day, aisle) %>% 
  filter(order_dow == 3, order_hour_of_day == 8) %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  filter(n >= 100) %>% 
  mutate(percentage = (n / sum(n))) %>% 
  plot_ly( labels = ~aisle, values = ~percentage, type = 'pie') %>%
  layout(title = "Pie plots for order number greater than 100 on 8,Wednesday")


```

